### ISSUE TITLE
A "?" at the end of a "print("text")" command.

### ISSUE THREAD

**Issue by soulgem** [wacossusca34/Consoles#13]
I am not sure if this is intentional (i hope it's not), but i found that when a put "print("Anything")" it adds a "?" at the end of the line.  Please note that I did NOT put it there in the code.
I put a "." not a ".?"...
Images here for proof.
![2015-06-30_08 55 44](https://cloud.githubusercontent.com/assets/2048135/8431197/d1abff40-1f05-11e5-9aa2-e68bd0f973d0.png)

![2015-06-30_08 51 08](https://cloud.githubusercontent.com/assets/2048135/8431145/80f1a0c8-1f05-11e5-9441-ed1c8354fe29.png)
![2015-06-30_08 51 02](https://cloud.githubusercontent.com/assets/2048135/8431146/80f2bb84-1f05-11e5-9c1f-d45bd02a88bc.png)

**Comment by wacossusca34** [comment]
Man, what is with old bugs popping up that I've fixed a long time ago? Maybe the last build was compiled with old classes. Argh.

Although, the last time I ran into this was with loading text data from URLs. This seems to be an internal encoding problem.. I assume your default Java encoding isn't UTF-8, but Consoles should be defaulting to UTF-8 anyway. I will look into fixing this.

The actual error: your Java encoding for text is causing newline characters to be more than one byte long and Consoles is truncating the character (and converting to UTF-8), therefore creating an invalid character that Consoles doesn't have a sprite for.

You can quickly fix this by launching your server with `java -Dfile.encoding=UTF-8 ...`, although I will look into having a fix that allows the server to run with any encoding.
