### ISSUE TITLE
httpGET and httpPOST error

### ISSUE THREAD

**Issue by rpiera** [wacossusca34/Consoles#16]
Both functions return an error when I try them. This script:
`removeRestrictions()
print(net.httpGET("http://some.dom/string.html"))`

returns this error:
![selection_035](https://cloud.githubusercontent.com/assets/5675226/10242523/a4c5d25e-68f1-11e5-9074-70eb55e3bbb7.png)

**Comment by wacossusca34** [comment]
actually, this is not a bug. That output is also not an error: it's actually a 'userdata' table, which is a Lua table wrapping for a java object. You need to use the following to actually get the content of the response:

    removeRestrictions()
    print(net.httpGET("http://some.dom/string.html"):getData())

If you have an issue with the `removeRestrictions` function, create a new issue
