### ISSUE TITLE
startup.lua overwritten on server restart

### ISSUE THREAD

**Issue by SeqSEE** [wacossusca34/Consoles#18]
In startup.lua there is the following rem'd out in the end:

        -- old prompt style, uncomment this to restore it
        -- getTerminal():setPrompt("%u@%h:%d$ ")

Seeing that, I decided to uncomment that part, since I love the look of a standard shell in Linux. When the server reloads the plugin on startup, it replaces this modified file so to speak, with the original and. I have write protected that file now to keep it the way I want. Since it seems unintentional, I would suggest checking for the files in the plugin folder and if it exists, don't write the default one over it. I could also just be reading the comments to yourself :p

**Comment by wacossusca34** [comment]
I think the funny part is that even though this has been around for a while, neither I or anyone else has tested the startup chunk to see if editing it worked.

I'll fix this when I dedicate a few days to sorting things out with consoles. I also have a huge amount of code changes from the version released on spigot so I still have yet to test those.

**Comment by wacossusca34** [comment]
Oh, and just so you know, you can make the `getTerminal():setPrompt(...)` call from any program in the console. The startup lua chunk is for code executed for when computers are started up in the server.
