### ISSUE TITLE
Plugin doesn't load on my server - Spigot for 1.8.6

### ISSUE THREAD

**Issue by Vellric** [wacossusca34/Consoles#3]
Hi, looks like a really nice plugin. I would want to use it. But the problem is the plugin don't want to load on my server. I put the error lines on pastebin: http://pastebin.com/ft3x04Ks
I hope to receive news! Thanks

**Comment by Vellric** [comment]
Java 8 for the win.

**Comment by wacossusca34** [comment]
Thanks for solving yourself :)
