### ISSUE TITLE
Socket/HTTP library?

### ISSUE THREAD

**Issue by soccermitchy** [wacossusca34/Consoles#4]
Is there a possibility of a (maybe admin-only?) library for communicating with things outside the server (for example, a web or IRC server)? I'm thinking I could make some sort of in-game currency or economy from powered off of Consoles using an external web server for things like a web interface.

**Comment by wacossusca34** [comment]
Hey! Cool suggestion.

I've been thinking about admin-only extensions and what not through Consoles. I'm not sure exactly how I would safely go about it... maybe executing programs with a `sudo` program that runs programs with an extra function pool added to Lua's globals... probably the easiest for me.

What kind of currency/economy system were you thinking about? I was thinking about making hooks into economy/auction/shop plugins that allows computers to integrate with them (putting items up for sale, showing economy graphcs, stats, etc) - sound like you have your own idea though.

The nice thing about the Lua library that I use is that it actually _compiles_ into Java bytecode, so I can have Java objects pretty seamlessly wrapped as Lua values and called normally. I could allow admin programs to do things like:

    socket = java.findClass("java.net.Socket", "127.0.0.1", 80)

Of course, I would have to have type mapping for the constructors of classes (but I already have most of that code done in the form of lambda <-> lua variable conversions), but this would be cool to give special programs the ability to use any Java class available at runtime.

Although, I would probably want to keep things simple like I have been with all my Lua functions already.

**Comment by soccermitchy** [comment]
I like the idea of a 'sudo' command for it, but would you be able to tell who is running the sudo command? Also, I like the idea of something like java.findClass, but imo something with an API like LuaSocket would be better (even just client-only would be nice)

**Comment by wacossusca34** [comment]
See how I did it in the source, I decided to actually go along with a lua function to do it all. It opens up a dialog that requires a player with the `comptuer.admin` permission to verify, and then the program runs unrestricted.

I already added HTTP POST/GET requests, untested, but it should be usable via:

    response = net.httpPOST("http://mywebsite.com/", "foo=12345&bar=\"test_POST\"")

The response is an object that you can call `response:getData()` and `response:getResponse()` on.

**Comment by wacossusca34** [comment]
Looks like it works so far. I'll just get better error handling for those requests and then I'll push the update :)

**Comment by wacossusca34** [comment]
Update has been pushed. You can now send HTTP POST/GET requests with unrestricted programs. Let me know if you run into any other issues.

**Comment by soccermitchy** [comment]
Do you have a build pushed out yet? Doing ./build.sh on my linux box didn't work since I don't have the stuff needed to compile spigot plugins.

**Comment by wacossusca34** [comment]
Yup! `1.5-beta` from the spigot page should work.
