### ISSUE TITLE
ASK. Option for turn off/on computer.

### ISSUE THREAD

**Issue by Mabus13** [wacossusca34/Consoles#48]
Need possibility for switchin off and unloading consoles which player not loged in, or use same command for it. Also need option for control access list players for your console.

**Comment by Mabus13** [comment]
And small problem for not oped players. If he logout from game and look in console. Then impossible to enter in game, bacause he cant type login command in game. That small but pity problem. =(

**Comment by wacossusca34** [comment]
> Need possibility for switchin off and unloading consoles which player not loged in, or use same command for it. Also need option for control access list players for your console.

There's not really an 'off' option for consoles because they don't actually _do_ anything if they are not running a program. The display doesn't update, no code is actually ran, and no program threads are even spawned. The only overhead an inactive computer has is the packets it has to send to individual players for the static content that was last displayed on the canvas.

> And small problem for not oped players. If he logout from game and look in console. Then impossible to enter in game, bacause he cant type login command in game. That small but pity problem. =(

I'm not sure I understand. He can't type into the console after relogging?

**Comment by Mabus13** [comment]
Yes maybe possible off to send to individual players for the static content that was last displayed on the canvas... If that option be included it be VERY VERY nice for many players projects.

Player cant type /L password command, because it overcaptured by console if  he look on that. I use Auth reload 3.5 and it problem real anoying. Because player cant move or change look before login.

**Comment by Mabus13** [comment]
And access list of players for console very very need too. ^_^

**Comment by Mabus13** [comment]
I found solve problem with login comand capture, i change prefix comands in config. Some later test it. ^_^

**Comment by wacossusca34** [comment]
> Player cant type /L password command, because it overcaptured by console if he look on that. I use Auth reload 3.5 and it problem real anoying. Because player cant move or change look before login.

Offline servers are not supported. Your own solution to change the command prefix is probably the best way to go.

> And access list of players for console very very need too. ^_^

'access list of players' makes no sense.

closing the issue since it is irrelevant.
