### ISSUE TITLE
Edit programs outside the game?

### ISSUE THREAD

**Issue by soccermitchy** [wacossusca34/Consoles#5]
Would it be possible for server owners to edit files from an external text editor (ie. notepad++) to make it easier to edit files?

**Comment by wacossusca34** [comment]
Yes, you can certainly do that, but you would have to use the `wget` program to grab the contents of your program from pastebin (or some other raw text hosting site). If you have an idea for something easier, I can look at doing that.

**Comment by soccermitchy** [comment]
I was thinking a way to open a program like a normal file on the server

**Comment by wacossusca34** [comment]
I could add a folder in the Consoles plugin folder called `programs`, where computers can grab/update from. Or even better, I could listen to changes on the filesystem and have computers link a file to a program in that folder and have it update when you change the contents of the program..

anything in particular?

**Comment by soccermitchy** [comment]
Maybe kind of a combination of both: A folder where files are shared between all computers, along with a computer-specific folder. Maybe also have autorun-type scripts in the computer specific folders.

**Comment by wacossusca34** [comment]
Hmm. Computers have their own format for filesystems (which I may rewrite at some point to have streamable support for the GZIP'd data and not having it all in memory) which are already stored with all the programs, but it's not really readable/editable outside of the plugin.

I could make the kernel call `/bin/init` when the computer starts, if it exists, for autorun scripts.

But a program folder with a pool of programs that computers can grab sounds pretty simple... I dunno. I could also add an `install.lua` program in the plugin `programs` folder for code to run on computers when they are first created.

**Comment by wacossusca34** [comment]
You should really add me on skype: `waccosusca34`, feature discussions aren't really best for the issue tracker :P

**Comment by soccermitchy** [comment]
Do you use Teamspeak or IRC? I don't have Skype installed on here.

**Comment by wacossusca34** [comment]
I certainly have a teamspeak client. If there's a server you regularly go on, I can hop on there.

**Comment by soccermitchy** [comment]
Sure, ts.nofla.me is where I am, my name on there is wolfmitchell.

**Comment by soccermitchy** [comment]
Reinstalled skype, and just added you.
